"use client";
import {useEffect,useMemo,useState} from "react";
type F={id:string;patientId:string;patientNumber:string;patientName:string;mobile:string;dueDate:string;purpose:string;assignedUserId:string;assignedUserName:string;notes:string;status:"PENDING"|"COMPLETED"|"CANCELLED";appointment?:{id:string;appointmentNumber:string;appointmentDate:string;appointmentTime:string;status:string}|null};
type P={id:string;patientNumber:string;name:string;mobile:string}; type S={id:string;name:string};
type View="ALL"|"DUE_TODAY"|"OVERDUE"|"UPCOMING"|"COMPLETED"|"CANCELLED";
function today(){return new Date().toLocaleDateString("en-CA")}
export default function FollowUps(){
 const[items,setItems]=useState<F[]>([]),[patients,setPatients]=useState<P[]>([]),[staff,setStaff]=useState<S[]>([]),[q,setQ]=useState(""),[open,setOpen]=useState(false),[editing,setEditing]=useState<F|null>(null),[saving,setSaving]=useState(false),[error,setError]=useState(""),[view,setView]=useState<View>("ALL");
 const empty={patientId:"",dueDate:today(),purpose:"",assignedUserId:"",notes:"",status:"PENDING" as const}; const[form,setForm]=useState(empty); const[dateFilter,setDateFilter]=useState(""); const[page,setPage]=useState(1); const pageSize=20;
 async function load(){const r=await fetch("/api/follow-ups",{cache:"no-store"});if(r.ok){const d=await r.json();setItems(d.followups);setPatients(d.patients);setStaff(d.staff)}}
 useEffect(()=>{void load()},[]);
 const filtered=useMemo(()=>{const t=today();return items.filter(x=>{
   const textMatch=!q.trim()||x.patientName.toLowerCase().includes(q.toLowerCase())||x.patientNumber.toLowerCase().includes(q.toLowerCase())||x.mobile.includes(q)||x.purpose.toLowerCase().includes(q.toLowerCase());
   const dateMatch=!dateFilter||x.dueDate===dateFilter;
   const viewMatch=view==="ALL"||(view==="DUE_TODAY"&&x.status==="PENDING"&&x.dueDate===t)||(view==="OVERDUE"&&x.status==="PENDING"&&x.dueDate<t)||(view==="UPCOMING"&&x.status==="PENDING"&&x.dueDate>t)||(view==="COMPLETED"&&x.status==="COMPLETED")||(view==="CANCELLED"&&x.status==="CANCELLED");
   return textMatch&&dateMatch&&viewMatch;
 }).sort((a,b)=>a.dueDate.localeCompare(b.dueDate)||a.patientName.localeCompare(b.patientName))},[items,q,dateFilter,view]);
 const totalPages=Math.max(1,Math.ceil(filtered.length/pageSize)); const safePage=Math.min(page,totalPages); const paged=filtered.slice((safePage-1)*pageSize,safePage*pageSize);
 function add(){setEditing(null);setForm({...empty,dueDate:today()});setError("");setOpen(true)}
 function edit(x:F){setEditing(x);setForm({patientId:x.patientId,dueDate:x.dueDate,purpose:x.purpose,assignedUserId:x.assignedUserId||"",notes:x.notes||"",status:x.status});setError("");setOpen(true)}
 async function action(followupId:string,action:"complete"|"cancel"){const message=action==="complete"?"Mark this follow-up as completed?":"Cancel this follow-up? It will remain in history.";if(!window.confirm(message))return;setError("");const r=await fetch("/api/follow-ups",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,followupId})});const d=await r.json();if(!r.ok){setError(d.error||"Unable to update follow-up.");return}await load()}
 function bookAppointment(x:F){window.location.href=`/app/appointments?book=1&followUpId=${encodeURIComponent(x.id)}&patientId=${encodeURIComponent(x.patientId)}&date=${encodeURIComponent(x.dueDate)}`}
 async function save(e:React.FormEvent){e.preventDefault();setSaving(true);setError("");const action=editing?"update":"create";const data=editing?{followupId:editing.id,...form}:form;const r=await fetch("/api/follow-ups",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,data})});const d=await r.json();setSaving(false);if(!r.ok){setError(d.error||"Unable to save follow-up.");return}setOpen(false);await load()}
 useEffect(()=>{setPage(1)},[q,dateFilter,view]);
 const t=today();
 return <div className="followups-page"><p className="eyebrow">Patient follow-up management</p><div className="page-header"><div><h1>Follow-ups</h1><p className="lead">Track due follow-ups, staff responsibilities, and follow-up history.</p></div><button className="button" onClick={add}>+ Add follow-up</button></div>
 {error&&<p className="error">{error}</p>}
 <div className="followup-summary"><button className={view==="ALL"?"active":""} onClick={()=>setView("ALL")}>All <strong>{items.length}</strong></button><button className={view==="DUE_TODAY"?"active":""} onClick={()=>setView("DUE_TODAY")}>Due today <strong>{items.filter(x=>x.status==="PENDING"&&x.dueDate===t).length}</strong></button><button className={view==="OVERDUE"?"active":""} onClick={()=>setView("OVERDUE")}>Overdue <strong>{items.filter(x=>x.status==="PENDING"&&x.dueDate<t).length}</strong></button><button className={view==="UPCOMING"?"active":""} onClick={()=>setView("UPCOMING")}>Upcoming <strong>{items.filter(x=>x.status==="PENDING"&&x.dueDate>t).length}</strong></button><button className={view==="COMPLETED"?"active":""} onClick={()=>setView("COMPLETED")}>Completed <strong>{items.filter(x=>x.status==="COMPLETED").length}</strong></button><button className={view==="CANCELLED"?"active":""} onClick={()=>setView("CANCELLED")}>Cancelled <strong>{items.filter(x=>x.status==="CANCELLED").length}</strong></button></div>
 <div className="toolbar followup-filters"><input className="catalogue-search" placeholder="Search patient, Patient ID, mobile or purpose..." value={q} onChange={e=>setQ(e.target.value)}/><label className="followup-date-filter">Follow-up date<input type="date" value={dateFilter} onChange={e=>setDateFilter(e.target.value)}/></label>{dateFilter&&<button className="secondary-button" type="button" onClick={()=>setDateFilter("")}>Clear date</button>}</div>
 <div className="card table-card lead-list"><div className="lead-table"><div className="lead-row followup-row lead-head"><span>Patient</span><span>Follow-up date</span><span>Purpose</span><span>Assigned to</span><span>Status</span><span>Actions</span></div>
 {paged.map(x=>{const state=x.status==="CANCELLED"?"cancelled":x.status==="COMPLETED"?"completed":x.dueDate<t?"overdue":x.dueDate===t?"due-today":"upcoming";return <div className={`lead-row followup-row followup-${state}`} key={x.id}><div><strong>{x.patientNumber}</strong><small>{x.patientName}<br/>{x.mobile}</small></div><span>{x.dueDate.split("-").reverse().join("-")}<small className="followup-state">{state==="overdue"?"Overdue":state==="due-today"?"Due today":state==="upcoming"?"Upcoming":state==="completed"?"Completed":"Cancelled"}</small></span><span>{x.purpose}</span><span>{x.assignedUserName||"—"}</span><span><span className={`followup-status status-${state}`}>{x.status}</span></span><span className="action-buttons">{x.status==="PENDING"&&!x.appointment&&<button className="text-button" onClick={()=>bookAppointment(x)}>Book appointment</button>}{x.status==="PENDING"&&x.appointment&&<button className="text-button" onClick={()=>{window.location.href=`/app/appointments?edit=${encodeURIComponent(x.appointment!.id)}&date=${encodeURIComponent(x.appointment!.appointmentDate)}`}}>Appointment booked · {x.appointment.appointmentNumber}</button>}{x.status==="PENDING"&&<><button className="text-button" onClick={()=>edit(x)}>Reschedule</button><button className="text-button success-text" onClick={()=>action(x.id,"complete")}>Complete</button><button className="text-button danger-text" onClick={()=>action(x.id,"cancel")}>Cancel</button></>}{x.status!=="PENDING"&&<button className="text-button" onClick={()=>edit(x)}>Edit</button>}</span></div>})}
 {filtered.length===0&&<div className="empty-state"><strong>No follow-ups found</strong><span>Try another filter or add a follow-up for a patient.</span></div>}</div></div>
 {filtered.length>0&&<div className="pagination followup-pagination"><button className="secondary-button" disabled={safePage<=1} onClick={()=>setPage(p=>Math.max(1,p-1))}>Previous</button><span>Page {safePage} of {totalPages} · {filtered.length} follow-ups</span><button className="secondary-button" disabled={safePage>=totalPages} onClick={()=>setPage(p=>Math.min(totalPages,p+1))}>Next</button></div>}
 {open&&<div className="catalogue-modal-backdrop"><div className="card form-card catalogue-modal"><div className="form-header"><div><h2>{editing?"Edit follow-up":"Add follow-up"}</h2><p className="muted">Schedule and assign patient follow-up.</p></div><button className="text-button" onClick={()=>setOpen(false)}>Close</button></div><form className="lead-form" onSubmit={save}><label className="full">Patient<select required value={form.patientId} onChange={e=>setForm(v=>({...v,patientId:e.target.value}))}><option value="">Select patient</option>{patients.map(p=><option key={p.id} value={p.id}>{p.patientNumber} · {p.name} · {p.mobile}</option>)}</select></label><label>Follow-up date<input required type="date" value={form.dueDate} onChange={e=>setForm(v=>({...v,dueDate:e.target.value}))}/></label><label>Purpose<input required value={form.purpose} onChange={e=>setForm(v=>({...v,purpose:e.target.value}))} placeholder="Review, next session, treatment follow-up..."/></label><label>Assigned to<select value={form.assignedUserId} onChange={e=>setForm(v=>({...v,assignedUserId:e.target.value}))}><option value="">Unassigned</option>{staff.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>{editing&&<label>Status<select value={form.status} onChange={e=>setForm(v=>({...v,status:e.target.value as F["status"]}))}><option value="PENDING">Pending</option><option value="COMPLETED">Completed</option><option value="CANCELLED">Cancelled</option></select></label>}<label className="full">Notes<textarea rows={4} value={form.notes} onChange={e=>setForm(v=>({...v,notes:e.target.value}))}/></label><div className="form-actions full"><button className="button" disabled={saving}>{saving?"Saving...":editing?"Save changes":"Add follow-up"}</button><button type="button" className="secondary-button" onClick={()=>setOpen(false)}>Cancel</button></div></form></div></div>}</div>
}