"use client";
import {useEffect,useState} from "react";
type F={id:string;patientId:string;patientNumber:string;patientName:string;mobile:string;dueDate:string;purpose:string;assignedUserId:string;assignedUserName:string;notes:string;status:"PENDING"|"COMPLETED"|"CANCELLED"}; type P={id:string;patientNumber:string;name:string;mobile:string}; type S={id:string;name:string};
export default function FollowUps(){const[items,setItems]=useState<F[]>([]),[patients,setPatients]=useState<P[]>([]),[staff,setStaff]=useState<S[]>([]),[q,setQ]=useState(""),[open,setOpen]=useState(false),[editing,setEditing]=useState<F|null>(null),[saving,setSaving]=useState(false),[error,setError]=useState("");
const empty={patientId:"",dueDate:new Date().toISOString().slice(0,10),purpose:"",assignedUserId:"",notes:"",status:"PENDING" as const}; const[form,setForm]=useState(empty);
async function load(){const r=await fetch("/api/follow-ups",{cache:"no-store"});if(r.ok){const d=await r.json();setItems(d.followups);setPatients(d.patients);setStaff(d.staff)}} useEffect(()=>{void load()},[]);
const filtered=items.filter(x=>!q.trim()||x.patientName.toLowerCase().includes(q.toLowerCase())||x.patientNumber.toLowerCase().includes(q.toLowerCase())||x.mobile.includes(q)||x.purpose.toLowerCase().includes(q.toLowerCase())).sort((a,b)=>a.dueDate.localeCompare(b.dueDate));
function add(){setEditing(null);setForm(empty);setError("");setOpen(true)} function edit(x:F){setEditing(x);setForm({patientId:x.patientId,dueDate:x.dueDate,purpose:x.purpose,assignedUserId:x.assignedUserId||"",notes:x.notes||"",status:x.status});setError("");setOpen(true)}
async function save(e:React.FormEvent){e.preventDefault();setSaving(true);setError("");const action=editing?"update":"create";const data=editing?{followupId:editing.id,...form}:form;const r=await fetch("/api/follow-ups",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,data})});const d=await r.json();setSaving(false);if(!r.ok){setError(d.error||"Unable to save follow-up.");return}setOpen(false);await load()}
return <><p className="eyebrow">Patient follow-up management</p><div className="page-header"><div><h1>Follow-ups</h1><p className="lead">Track due follow-ups and staff responsibilities.</p></div><button className="button" onClick={add}>+ Add follow-up</button></div>{error&&<p className="error">{error}</p>}<div className="toolbar"><input className="catalogue-search" placeholder="Search patient, Patient ID, mobile or purpose..." value={q} onChange={e=>setQ(e.target.value)}/></div><div className="card table-card lead-list"><div className="lead-table"><div className="lead-row followup-row lead-head"><span>Patient</span><span>Follow-up date</span><span>Purpose</span><span>Assigned to</span><span>Status</span><span>Actions</span></div>{filtered.map(x=><div className="lead-row followup-row" key={x.id}><div><strong>{x.patientNumber}</strong><small>{x.patientName}<br/>{x.mobile}</small></div><span>{x.dueDate.split("-").reverse().join("-")}</span><span>{x.purpose}</span><span>{x.assignedUserName||"—"}</span><span className={x.status==="PENDING"?"status-active":"status-inactive"}>{x.status}</span><span><button className="text-button" onClick={()=>edit(x)}>Edit</button></span></div>)}{filtered.length===0&&<div className="empty-state"><strong>No follow-ups yet</strong><span>Add a follow-up for a patient.</span></div>}</div></div>
{open&&<div className="catalogue-modal-backdrop"><div className="card form-card catalogue-modal"><div className="form-header"><div><h2>{editing?"Edit follow-up":"Add follow-up"}</h2><p className="muted">Schedule and assign patient follow-up.</p></div><button className="text-button" onClick={()=>setOpen(false)}>Close</button></div><form className="lead-form" onSubmit={save}><label className="full">Patient<select required value={form.patientId} onChange={e=>setForm(v=>({...v,patientId:e.target.value}))}><option value="">Select patient</option>{patients.map(p=><option key={p.id} value={p.id}>{p.patientNumber} · {p.name} · {p.mobile}</option>)}</select></label><label>Follow-up date<input required type="date" value={form.dueDate} onChange={e=>setForm(v=>({...v,dueDate:e.target.value}))}/></label><label>Purpose<input required value={form.purpose} onChange={e=>setForm(v=>({...v,purpose:e.target.value}))} placeholder="Review, next session, treatment follow-up..."/></label><label>Assigned to<select value={form.assignedUserId} onChange={e=>setForm(v=>({...v,assignedUserId:e.target.value}))}><option value="">Unassigned</option>{staff.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>{editing&&<label>Status<select value={form.status} onChange={e=>setForm(v=>({...v,status:e.target.value as F["status"]}))}><option value="PENDING">Pending</option><option value="COMPLETED">Completed</option><option value="CANCELLED">Cancelled</option></select></label>}<label className="full">Notes<textarea rows={4} value={form.notes} onChange={e=>setForm(v=>({...v,notes:e.target.value}))}/></label><div className="form-actions full"><button className="button" disabled={saving}>{saving?"Saving...":editing?"Save changes":"Add follow-up"}</button><button type="button" className="secondary-button" onClick={()=>setOpen(false)}>Cancel</button></div></form></div></div>}</>}