-- Baseline migration for the secure platform foundation.
-- Apply with `prisma migrate deploy`; never use `prisma db push` in production.
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE TYPE "RoleName" AS ENUM ('ADMIN', 'DOCTOR', 'RECEPTIONIST_TELECALLER', 'THERAPIST');

CREATE TABLE "Organization" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(), "name" TEXT NOT NULL, "slug" TEXT NOT NULL UNIQUE, "isActive" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "ClinicLocation" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(), "organizationId" UUID NOT NULL REFERENCES "Organization"("id") ON DELETE RESTRICT, "name" TEXT NOT NULL, "code" TEXT NOT NULL, "address" TEXT, "timezone" TEXT NOT NULL DEFAULT 'Asia/Kolkata', "isActive" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE ("organizationId", "code"));
CREATE TABLE "User" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(), "email" TEXT NOT NULL UNIQUE, "name" TEXT, "passwordHash" TEXT, "emailVerified" TIMESTAMPTZ, "isActive" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "StaffProfile" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(), "userId" UUID NOT NULL UNIQUE REFERENCES "User"("id") ON DELETE RESTRICT, "organizationId" UUID NOT NULL REFERENCES "Organization"("id") ON DELETE RESTRICT, "clinicLocationId" UUID REFERENCES "ClinicLocation"("id") ON DELETE RESTRICT, "employeeCode" TEXT, "jobTitle" TEXT, "isActive" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE ("organizationId", "employeeCode"));
CREATE TABLE "Role" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(), "name" "RoleName" NOT NULL UNIQUE, "description" TEXT NOT NULL, "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Permission" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(), "key" TEXT NOT NULL UNIQUE, "description" TEXT NOT NULL, "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "RolePermission" ("roleId" UUID NOT NULL REFERENCES "Role"("id") ON DELETE CASCADE, "permissionId" UUID NOT NULL REFERENCES "Permission"("id") ON DELETE CASCADE, PRIMARY KEY ("roleId", "permissionId"));
CREATE TABLE "UserRole" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(), "userId" UUID NOT NULL REFERENCES "User"("id") ON DELETE RESTRICT, "roleId" UUID NOT NULL REFERENCES "Role"("id") ON DELETE RESTRICT, "organizationId" UUID NOT NULL REFERENCES "Organization"("id") ON DELETE RESTRICT, "clinicLocationId" UUID REFERENCES "ClinicLocation"("id") ON DELETE RESTRICT, "scopeKey" TEXT NOT NULL, "assignedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, "assignedByUserId" UUID, UNIQUE ("userId", "roleId", "organizationId", "scopeKey"));
CREATE TABLE "AuditEvent" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(), "organizationId" UUID NOT NULL REFERENCES "Organization"("id") ON DELETE RESTRICT, "actorUserId" UUID REFERENCES "User"("id") ON DELETE SET NULL, "action" TEXT NOT NULL, "resourceType" TEXT NOT NULL, "resourceId" TEXT, "metadata" JSONB, "occurredAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, "requestId" TEXT, "ipAddress" TEXT, "userAgent" TEXT);
CREATE INDEX "AuditEvent_organizationId_occurredAt_idx" ON "AuditEvent"("organizationId", "occurredAt");
CREATE INDEX "AuditEvent_resourceType_resourceId_idx" ON "AuditEvent"("resourceType", "resourceId");

CREATE TABLE "Account" ("id" TEXT PRIMARY KEY, "userId" UUID NOT NULL REFERENCES "User"("id") ON DELETE CASCADE, "type" TEXT NOT NULL, "provider" TEXT NOT NULL, "providerAccountId" TEXT NOT NULL, "refresh_token" TEXT, "access_token" TEXT, "expires_at" INTEGER, "token_type" TEXT, "scope" TEXT, "id_token" TEXT, "session_state" TEXT, UNIQUE ("provider", "providerAccountId"));
CREATE TABLE "Session" ("id" TEXT PRIMARY KEY, "sessionToken" TEXT NOT NULL UNIQUE, "userId" UUID NOT NULL REFERENCES "User"("id") ON DELETE CASCADE, "expires" TIMESTAMPTZ NOT NULL);
CREATE TABLE "VerificationToken" ("identifier" TEXT NOT NULL, "token" TEXT NOT NULL UNIQUE, "expires" TIMESTAMPTZ NOT NULL, UNIQUE ("identifier", "token"));
