"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Patient={id:string;patientNumber:string;name:string;mobile:string};
type CatalogItem={id:string;type:"TREATMENT"|"PACKAGE";name:string;price:number;category?:string;sessions?:number};
type Line={type:"TREATMENT"|"PACKAGE";catalogueId:string;name:string;quantity:number;unitPrice:number;discountAmount:number};
type Payment={paymentId:string;receiptNumber:string;amount:number;method:string;paidAt:string;notes:string};
type Bill={id:string;billNumber:string;financialYear?:string;createdAt?:string;createdByUserId?:string;billDate:string;patientId:string;patientNumber:string;patientName:string;mobile:string;lineItems:Line[];subtotal:number;billDiscount:number;taxableAmount:number;taxRate:number;taxAmount:number;grandTotal:number;amountPaid:number;balanceDue:number;paymentStatus:string;payments:Payment[];notes?:string};

const methods=[["CASH","Cash"],["UPI","UPI"],["CARD","Card"],["BANK_TRANSFER","Bank Transfer"],["OTHER","Other"]];
const money=(n:number)=>"₹"+Number(n||0).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2});
const paymentLabel=(v:string)=>methods.find(([key])=>key===v)?.[1]??v;

export default function BillingPage(){
 const [catalogue,setCatalogue]=useState<CatalogItem[]>([]),[bills,setBills]=useState<Bill[]>([]),[search,setSearch]=useState(""),[open,setOpen]=useState(false),[paymentBill,setPaymentBill]=useState<Bill|null>(null),[viewBill,setViewBill]=useState<Bill|null>(null),[editBill,setEditBill]=useState<Bill|null>(null),[receiptBill,setReceiptBill]=useState<Bill|null>(null),[editPayment,setEditPayment]=useState<{bill:Bill;payment:Payment}|null>(null),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const [catalogueQuery,setCatalogueQuery]=useState(""),[patientQuery,setPatientQuery]=useState(""),[patients,setPatients]=useState<Patient[]>([]),[selectedPatient,setSelectedPatient]=useState<Patient|null>(null);
 const [lines,setLines]=useState<Line[]>([]),[billDiscount,setBillDiscount]=useState("0"),[taxRate,setTaxRate]=useState("0"),[notes,setNotes]=useState("");
 const [paymentAmount,setPaymentAmount]=useState(""),[paymentMethod,setPaymentMethod]=useState("CASH"),[paymentNotes,setPaymentNotes]=useState("");

 async function load(){const r=await fetch("/api/billing",{cache:"no-store"});if(r.ok){const d=await r.json();setCatalogue([...d.treatments,...d.packages]);setBills(d.bills);}}
 useEffect(()=>{void load()},[]);
 async function searchPatients(q:string){setPatientQuery(q);setSelectedPatient(null);if(q.trim().length<2){setPatients([]);return}const r=await fetch("/api/patients?q="+encodeURIComponent(q.trim())+"&page=1&pageSize=10",{cache:"no-store"});if(r.ok)setPatients((await r.json()).patients)}
 function addLine(item:CatalogItem){setLines(old=>[...old,{type:item.type,catalogueId:item.id,name:item.name,quantity:1,unitPrice:item.price,discountAmount:0}]);}
 function updateLine(index:number,key:keyof Line,value:string|number){setLines(old=>old.map((line,i)=>i===index?{...line,[key]:typeof value==="string"&&key!=="type"&&key!=="catalogueId"&&key!=="name"?Number(value):value}:line))}
 function removeLine(index:number){setLines(old=>old.filter((_,i)=>i!==index))}
 const subtotal=useMemo(()=>lines.reduce((s,l)=>s+Math.max(0,l.unitPrice*l.quantity-Math.min(l.unitPrice*l.quantity,l.discountAmount)),0),[lines]);
 const discount=Math.min(subtotal,Number(billDiscount)||0);const taxable=Math.max(0,subtotal-discount);const tax=Number((taxable*(Number(taxRate)||0)/100).toFixed(2));const grand=Number((taxable+tax).toFixed(2));
 const filteredCatalogue=catalogue.filter(item=>!catalogueQuery.trim()||item.name.toLowerCase().includes(catalogueQuery.trim().toLowerCase()));
 const filtered=bills.filter(b=>!search.trim()||b.billNumber.toLowerCase().includes(search.toLowerCase())||b.patientName.toLowerCase().includes(search.toLowerCase())||b.patientNumber.toLowerCase().includes(search.toLowerCase())||b.mobile.includes(search.trim()));

 function resetBillForm(){setSelectedPatient(null);setPatientQuery("");setPatients([]);setLines([]);setBillDiscount("0");setTaxRate("0");setNotes("");setCatalogueQuery("");}
 function newBill(){resetBillForm();setError("");setOpen(true)}
 function startEditBill(b:Bill){setEditBill(b);setSelectedPatient({id:b.patientId,patientNumber:b.patientNumber,name:b.patientName,mobile:b.mobile});setLines(b.lineItems.map(l=>({...l})));setBillDiscount(String(b.billDiscount??0));setTaxRate(String(b.taxRate??0));setNotes(b.notes??"");setCatalogueQuery("");setError("")}
 function closeAll(){setOpen(false);setPaymentBill(null);setViewBill(null);setEditBill(null);setReceiptBill(null);setEditPayment(null);setError("")}

 async function createBill(e:FormEvent){e.preventDefault();if(!selectedPatient){setError("Please select a patient.");return}if(!lines.length){setError("Add at least one treatment or package.");return}setSaving(true);setError("");const form=new FormData(e.currentTarget);const initialPayment=Number(form.get("initialPayment")||0);const paymentMethod=String(form.get("paymentMethod")||"CASH");const paymentNotes=String(form.get("paymentNotes")||"");const r=await fetch("/api/billing",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({patientId:selectedPatient.id,lineItems:lines,billDiscount:discount,taxRate:Number(taxRate)||0,notes,initialPayment,paymentMethod,paymentNotes})});const d=await r.json();setSaving(false);if(!r.ok){setError(d.error||"Unable to create bill.");return}setOpen(false);await load();setViewBill(d.bill)}
 async function saveBillEdit(e:FormEvent){e.preventDefault();if(!editBill||!lines.length){setError("Add at least one treatment or package.");return}setSaving(true);setError("");const r=await fetch("/api/billing",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"edit-bill",billId:editBill.id,lineItems:lines,billDiscount:discount,taxRate:Number(taxRate)||0,notes})});const d=await r.json();setSaving(false);if(!r.ok){setError(d.error||"Unable to edit bill.");return}setEditBill(null);await load();setViewBill(d.bill)}
 function openPayment(b:Bill){setPaymentBill(b);setPaymentAmount(b.balanceDue.toFixed(2));setPaymentMethod("CASH");setPaymentNotes("");setError("")}
 async function savePayment(e:FormEvent){e.preventDefault();if(!paymentBill)return;setSaving(true);setError("");const r=await fetch("/api/billing",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"payment",billId:paymentBill.id,amount:Number(paymentAmount),method:paymentMethod,notes:paymentNotes})});const d=await r.json();setSaving(false);if(!r.ok){setError(d.error||"Unable to record payment.");return}setPaymentBill(null);await load()}
 function openEditPayment(b:Bill,p:Payment){setEditPayment({bill:b,payment:p});setPaymentAmount(String(p.amount));setPaymentMethod(p.method);setPaymentNotes(p.notes||"");setError("")}
 async function savePaymentEdit(e:FormEvent){e.preventDefault();if(!editPayment)return;setSaving(true);setError("");const r=await fetch("/api/billing",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"edit-payment",billId:editPayment.bill.id,paymentId:editPayment.payment.paymentId,amount:Number(paymentAmount),method:paymentMethod,notes:paymentNotes})});const d=await r.json();setSaving(false);if(!r.ok){setError(d.error||"Unable to edit receipt.");return}setEditPayment(null);await load()}
 function printBill(b:Bill){const w=window.open("","_blank","width=800,height=900");if(!w)return;const created=new Date(b.createdAt||b.billDate);const dateText=created.toLocaleDateString("en-IN");const timeText=created.toLocaleTimeString("en-IN",{hour:"2-digit",minute:"2-digit"});w.document.write(`<!doctype html><html><head><title>${b.billNumber}</title><style>body{font-family:Arial;padding:32px;color:#222}table.items{width:100%;border-collapse:collapse;margin-top:24px}table.items th,table.items td{padding:8px;border-bottom:1px solid #ddd;text-align:left}table.items th:last-child,table.items td:last-child{text-align:right}.header{display:flex;justify-content:space-between;gap:40px;margin-top:22px}.patient{flex:1}.invoice-meta{text-align:right;min-width:240px}.invoice-meta div{margin-bottom:5px}.totals{margin:20px 0 0 auto;width:320px}.row{display:flex;justify-content:space-between;padding:4px}.total{font-weight:bold;border-top:2px solid #222;margin-top:8px;padding-top:8px}.footer{margin-top:48px;display:flex;justify-content:space-between;align-items:end}.signature{min-width:260px}.creator{font-size:12px;color:#555}</style></head><body><h1>Dr Dolly's Skintech Clinic</h1><p>Pratap Nagar, Nagpur, Maharashtra 440022</p><hr><div class="header"><div class="patient"><b>Patient:</b> ${b.patientNumber} · ${b.patientName}<br><b>Mobile:</b> ${b.mobile}</div><div class="invoice-meta"><div><b>Invoice No:</b> ${b.billNumber}</div><div><b>Date:</b> ${dateText}</div><div><b>Time:</b> ${timeText}</div></div></div><table class="items"><thead><tr><th>SN</th><th>Description</th><th>Qty</th><th>Amount</th></tr></thead><tbody>${b.lineItems.map((l,i)=>`<tr><td>${i+1}</td><td>${l.name}</td><td>${l.quantity}</td><td>${money(l.unitPrice*l.quantity-l.discountAmount)}</td></tr>`).join("")}</tbody></table><div class="totals"><div class="row"><span>Subtotal</span><span>${money(b.subtotal)}</span></div><div class="row"><span>Discount</span><span>${money(b.billDiscount)}</span></div><div class="row"><span>Tax</span><span>${money(b.taxAmount)}</span></div><div class="row total"><span>Total</span><span>${money(b.grandTotal)}</span></div><div class="row"><span>Paid</span><span>${money(b.amountPaid)}</span></div><div class="row"><span>Balance</span><span>${money(b.balanceDue)}</span></div></div><div class="footer"><div class="creator">Created by User ID: ${b.createdByUserId||b.actorUserId||"N/A"}</div><div class="signature">Authorized Signature: ____________________</div></div><script>window.print();</script></body></html>`);w.document.close()}
 function printReceipt(b:Bill,p:Payment){const w=window.open("","_blank","width=700,height=700");if(!w)return;w.document.write(`<!doctype html><html><head><title>${p.receiptNumber}</title><style>body{font-family:Arial;padding:32px;color:#222}.box{border:1px solid #ddd;padding:20px;margin-top:20px}.row{display:flex;justify-content:space-between;padding:6px 0}</style></head><body><h1>Dr Dolly's Skintech Clinic</h1><p>Pratap Nagar, Nagpur, Maharashtra 440022</p><h2>Payment Receipt</h2><div class="box"><div class="row"><b>Receipt No.</b><span>${p.receiptNumber}</span></div><div class="row"><b>Invoice No.</b><span>${b.billNumber}</span></div><div class="row"><b>Patient</b><span>${b.patientNumber} · ${b.patientName}</span></div><div class="row"><b>Date</b><span>${new Date(p.paidAt).toLocaleString("en-IN")}</span></div><div class="row"><b>Payment Method</b><span>${paymentLabel(p.method)}</span></div><div class="row"><b>Amount Received</b><span>${money(p.amount)}</span></div><div class="row"><b>Balance After Payment</b><span>${money(b.balanceDue)}</span></div></div><p style="margin-top:40px">Authorized Signature: ____________________</p><script>window.print();</script></body></html>`);w.document.close()}

 const formModal=(editing:boolean)=><div className="catalogue-modal-backdrop bill-modal-backdrop"><div className="card form-card catalogue-modal bill-modal"><div className="bill-modal-header"><div><span className="bill-modal-kicker">Finance</span><h2>{editing?"Edit invoice":"Create new invoice"}</h2><p>{editing?<>Invoice <strong>{editBill?.billNumber}</strong></>:<>Invoice number will be generated automatically after saving.</>}</p></div><button className="bill-close" type="button" aria-label="Close invoice form" onClick={()=>editing?setEditBill(null):setOpen(false)}>×</button></div><form className="bill-form" onSubmit={editing?saveBillEdit:createBill}>
 <section className="bill-section"><div className="bill-section-title"><span className="bill-step">1</span><div><h3>Patient</h3><p>Select the patient for this invoice.</p></div></div><label className="full bill-field">{selectedPatient?<div className="bill-patient-selected"><div><strong>{selectedPatient.patientNumber}</strong><span>{selectedPatient.name}</span></div><div><span>{selectedPatient.mobile}</span><button type="button" className="text-button" onClick={()=>{setSelectedPatient(null);setPatientQuery("")}}>Change</button></div></div>:<><span className="sr-only">Search patient</span><input value={patientQuery} onChange={e=>void searchPatients(e.target.value)} placeholder="Search by patient name, mobile or Patient ID" autoComplete="off"/>{patientQuery.trim().length>=2&&<div className="bill-search-results">{patients.length?patients.map(p=><button className="bill-search-result" type="button" key={p.id} onClick={()=>{setSelectedPatient(p);setPatients([])}}><span><strong>{p.patientNumber}</strong> · {p.name}</span><small>{p.mobile}</small></button>):<span className="muted">No matching patients found.</span>}</div>}</>}</label></section>
 <section className="bill-section"><div className="bill-section-title"><span className="bill-step">2</span><div><h3>Services & packages</h3><p>Add the treatments or packages being billed.</p></div></div><div className="bill-items-box">{lines.length===0&&<div className="bill-empty-items"><strong>No services added yet</strong><span>Search below to add a treatment or package.</span></div>}{lines.length>0&&<div className="bill-items-list">{lines.map((l,i)=><div className="bill-item-row" key={l.catalogueId+"-"+i}><div className="bill-item-name"><span>{i+1}</span><strong>{l.name}</strong></div><label>Qty<input type="number" min="1" value={l.quantity} onChange={e=>updateLine(i,"quantity",e.target.value)}/></label><label>Price<input type="number" min="0" value={l.unitPrice} onChange={e=>updateLine(i,"unitPrice",e.target.value)}/></label><label>Discount<input type="number" min="0" value={l.discountAmount} onChange={e=>updateLine(i,"discountAmount",e.target.value)}/></label><button type="button" className="bill-remove" onClick={()=>removeLine(i)}>Remove</button></div>)}</div>}<div className="bill-catalogue-search"><span>+ Add treatment or package</span><input value={catalogueQuery} onChange={e=>setCatalogueQuery(e.target.value)} placeholder="Type to search, e.g. PRP, Hydrafacial, Gluta, Eyebrow..." aria-label="Search treatment or package"/>{catalogueQuery.trim()&&<div className="bill-search-results">{filteredCatalogue.length?filteredCatalogue.slice(0,10).map(item=><button type="button" className="bill-search-result" key={item.id+"-"+item.type} onClick={()=>{addLine(item);setCatalogueQuery("")}}><span><strong>{item.type==="PACKAGE"?"Package":"Treatment"}</strong> · {item.name}</span><small>{money(item.price)}</small></button>):<span className="muted">No matching treatment or package found.</span>}</div>}</div></div></section>
 <section className="bill-section"><div className="bill-section-title"><span className="bill-step">3</span><div><h3>Payment & adjustments</h3><p>Optional at the time of invoice creation.</p></div></div><div className="bill-two-col">{!editing&&<><label className="bill-field">Initial payment<input name="initialPayment" type="number" min="0" max={grand} step="0.01" defaultValue="0"/><small>Enter the amount received today. Leave 0 if unpaid.</small></label><label className="bill-field">Payment method<select name="paymentMethod" defaultValue="CASH">{methods.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></>}<label className="bill-field">Invoice discount<input type="number" min="0" max={subtotal} value={billDiscount} onChange={e=>setBillDiscount(e.target.value)}/></label><label className="bill-field">Tax rate (%)<input type="number" min="0" max="100" step="0.01" value={taxRate} onChange={e=>setTaxRate(e.target.value)}/></label></div><label className="bill-field full">Notes<textarea rows={2} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Optional notes for this invoice"/></label></section>
 <section className="bill-summary-section"><div><span>Grand total</span><strong>{money(grand)}</strong></div>{!editing&&<div><span>Initial payment</span><strong>{money(Number((document.querySelector('input[name="initialPayment"]') as HTMLInputElement)?.value||0))}</strong></div>}<div><span>Balance due</span><strong>{money(Math.max(0,grand-(!editing?Number((document.querySelector('input[name="initialPayment"]') as HTMLInputElement)?.value||0):Number(editBill?.amountPaid||0))))}</strong></div></section>
 <div className="bill-form-footer"><button className="button" disabled={saving}>{saving?"Saving...":editing?"Save invoice changes":"Create invoice"}</button><button type="button" className="secondary-button" onClick={()=>editing?setEditBill(null):setOpen(false)}>Cancel</button></div></form></div></div>

 return <><p className="eyebrow">Finance</p><div className="page-header"><div><h1>Billing & Payments</h1><p className="lead">Invoices and payment receipts are permanent records and can be viewed or edited.</p></div><button className="button" onClick={newBill}>+ New invoice</button></div>
 {error&&<p className="error">{error}</p>}
 {open&&formModal(false)}{editBill&&formModal(true)}
 {paymentBill&&<div className="catalogue-modal-backdrop"><div className="card form-card catalogue-modal"><div className="form-header"><div><h2>Record payment</h2><p className="muted">{paymentBill.billNumber} · Balance {money(paymentBill.balanceDue)}</p></div><button className="text-button" type="button" onClick={()=>setPaymentBill(null)}>Close</button></div><form className="lead-form" onSubmit={savePayment}><label>Amount (₹)<input required type="number" min="0.01" max={paymentBill.balanceDue} step="0.01" value={paymentAmount} onChange={e=>setPaymentAmount(e.target.value)}/></label><label>Payment method<select value={paymentMethod} onChange={e=>setPaymentMethod(e.target.value)}>{methods.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="full">Notes<textarea rows={2} value={paymentNotes} onChange={e=>setPaymentNotes(e.target.value)}/></label><div className="form-actions full"><button className="button" disabled={saving}>{saving?"Saving...":"Record payment"}</button><button type="button" className="secondary-button" onClick={()=>setPaymentBill(null)}>Cancel</button></div></form></div></div>}
 {editPayment&&<div className="catalogue-modal-backdrop"><div className="card form-card catalogue-modal"><div className="form-header"><div><h2>Edit payment receipt</h2><p className="muted">{editPayment.payment.receiptNumber} · {editPayment.bill.billNumber}</p></div><button className="text-button" type="button" onClick={()=>setEditPayment(null)}>Close</button></div><form className="lead-form" onSubmit={savePaymentEdit}><label>Amount (₹)<input required type="number" min="0.01" max={editPayment.payment.amount+editPayment.bill.balanceDue} step="0.01" value={paymentAmount} onChange={e=>setPaymentAmount(e.target.value)}/></label><label>Payment method<select value={paymentMethod} onChange={e=>setPaymentMethod(e.target.value)}>{methods.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="full">Notes<textarea rows={2} value={paymentNotes} onChange={e=>setPaymentNotes(e.target.value)}/></label><div className="form-actions full"><button className="button" disabled={saving}>{saving?"Saving...":"Save receipt changes"}</button><button type="button" className="secondary-button" onClick={()=>setEditPayment(null)}>Cancel</button></div></form></div></div>}
 {viewBill&&<div className="catalogue-modal-backdrop"><div className="card form-card catalogue-modal"><div className="form-header"><div><h2>Invoice {viewBill.billNumber}</h2><p className="muted">Financial Year {viewBill.financialYear}</p></div><button className="text-button" onClick={()=>setViewBill(null)}>Close</button></div><p><b>Patient:</b> {viewBill.patientNumber} · {viewBill.patientName} · {viewBill.mobile}</p><div className="card"><strong>Items</strong>{viewBill.lineItems.map((l,i)=><div className="row" key={i}><span>{l.name} × {l.quantity}</span><span>{money(l.total??l.unitPrice*l.quantity-l.discountAmount)}</span></div>)}<div className="row total"><strong>Total</strong><strong>{money(viewBill.grandTotal)}</strong></div><div className="row"><span>Paid</span><span>{money(viewBill.amountPaid)}</span></div><div className="row"><span>Balance</span><span>{money(viewBill.balanceDue)}</span></div></div><div className="form-actions"><button className="button" onClick={()=>{setViewBill(null);startEditBill(viewBill)}}>Edit invoice</button><button className="secondary-button" onClick={()=>printBill(viewBill)}>Print</button><button className="secondary-button" onClick={()=>setReceiptBill(viewBill)}>Receipts ({viewBill.payments.length})</button></div></div></div>}
 {receiptBill&&<div className="catalogue-modal-backdrop"><div className="card form-card catalogue-modal"><div className="form-header"><div><h2>Payment receipts</h2><p className="muted">{receiptBill.billNumber} · {receiptBill.patientName}</p></div><button className="text-button" onClick={()=>setReceiptBill(null)}>Close</button></div>{receiptBill.payments.length?receiptBill.payments.map(p=><div className="card" key={p.paymentId} style={{marginBottom:8}}><div className="row"><strong>{p.receiptNumber}</strong><span>{money(p.amount)}</span></div><div className="row"><span>{paymentLabel(p.method)}</span><span>{new Date(p.paidAt).toLocaleString("en-IN")}</span></div><div className="row-actions"><button className="text-button" onClick={()=>openEditPayment(receiptBill,p)}>Edit</button><button className="text-button" onClick={()=>printReceipt(receiptBill,p)}>View / Print</button></div></div>):<p className="muted">No payment receipts recorded.</p>}</div></div>}
 <div className="toolbar"><input className="catalogue-search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search invoice, patient name, Patient ID or mobile..." /></div>
 <div className="card table-card lead-list"><div className="lead-table"><div className="lead-row catalogue-package-row lead-head"><span>Invoice No.</span><span>Date</span><span>Patient</span><span>Total</span><span>Paid</span><span>Balance</span><span>Status</span><span>Actions</span></div>{filtered.map(b=><div className="lead-row catalogue-package-row" key={b.id}><strong>{b.billNumber}</strong><span>{b.billDate.split("-").reverse().join("-")}</span><span>{b.patientNumber} · {b.patientName}</span><span>{money(b.grandTotal)}</span><span>{money(b.amountPaid)}</span><span>{money(b.balanceDue)}</span><span className={b.paymentStatus==="PAID"?"status-active":"status-inactive"}>{b.paymentStatus==="PAID"?"Paid":b.paymentStatus==="PARTIALLY_PAID"?"Partially Paid":"Unpaid"}</span><span className="row-actions"><button className="text-button" onClick={()=>setViewBill(b)}>View</button><button className="text-button" onClick={()=>startEditBill(b)}>Edit</button>{b.balanceDue>0&&<button className="text-button" onClick={()=>openPayment(b)}>Payment</button>}{b.payments.length>0&&<button className="text-button" onClick={()=>setReceiptBill(b)}>Receipts</button>}<button className="text-button" onClick={()=>printBill(b)}>Print</button></span></div>)}{filtered.length===0&&<div className="empty-state"><strong>No invoices found</strong><span>Create a new invoice to start billing.</span></div>}</div></div>
 </>;
}
