"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Patient={id:string;patientNumber:string;name:string;mobile:string};
type CatalogItem={id:string;type:"TREATMENT"|"PACKAGE";name:string;price:number;category?:string;sessions?:number};
type Line={type:"TREATMENT"|"PACKAGE";catalogueId:string;name:string;quantity:number;unitPrice:number;discountAmount:number};
type Bill={id:string;billNumber:string;billDate:string;patientId:string;patientNumber:string;patientName:string;mobile:string;lineItems:Line[];subtotal:number;billDiscount:number;taxableAmount:number;taxRate:number;taxAmount:number;grandTotal:number;amountPaid:number;balanceDue:number;paymentStatus:string;payments:Array<{amount:number;method:string;paidAt:string;notes:string}>;notes?:string};

const methods=[["CASH","Cash"],["UPI","UPI"],["CARD","Card"],["BANK_TRANSFER","Bank Transfer"],["OTHER","Other"]];
const money=(n:number)=>"₹"+Number(n||0).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2});

export default function BillingPage(){
 const [catalogue,setCatalogue]=useState<CatalogItem[]>([]),[bills,setBills]=useState<Bill[]>([]),[search,setSearch]=useState(""),[open,setOpen]=useState(false),[paymentBill,setPaymentBill]=useState<Bill|null>(null),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const [patientQuery,setPatientQuery]=useState(""),[patients,setPatients]=useState<Patient[]>([]),[selectedPatient,setSelectedPatient]=useState<Patient|null>(null);
 const [lines,setLines]=useState<Line[]>([]),[billDiscount,setBillDiscount]=useState("0"),[taxRate,setTaxRate]=useState("0"),[notes,setNotes]=useState("");
 const [paymentAmount,setPaymentAmount]=useState(""),[paymentMethod,setPaymentMethod]=useState("CASH"),[paymentNotes,setPaymentNotes]=useState("");
 async function load(){const r=await fetch("/api/billing",{cache:"no-store"});if(r.ok){const d=await r.json();setCatalogue([...d.treatments,...d.packages]);setBills(d.bills);}}
 useEffect(()=>{void load()},[]);
 async function searchPatients(q:string){setPatientQuery(q);setSelectedPatient(null);if(q.trim().length<2){setPatients([]);return}const r=await fetch("/api/patients?q="+encodeURIComponent(q.trim())+"&page=1&pageSize=10",{cache:"no-store"});if(r.ok)setPatients((await r.json()).patients)}
 function addLine(item:CatalogItem){setLines((old)=>[...old,{type:item.type,catalogueId:item.id,name:item.name,quantity:1,unitPrice:item.price,discountAmount:0}]);}
 function updateLine(index:number,key:keyof Line,value:string|number){setLines((old)=>old.map((line,i)=>i===index?{...line,[key]:typeof value==="string"&&key!=="type"&&key!=="catalogueId"&&key!=="name"?Number(value):value}:line))}
 function removeLine(index:number){setLines((old)=>old.filter((_,i)=>i!==index))}
 const subtotal=useMemo(()=>lines.reduce((s,l)=>s+Math.max(0,l.unitPrice*l.quantity-Math.min(l.unitPrice*l.quantity,l.discountAmount)),0),[lines]);
 const discount=Math.min(subtotal,Number(billDiscount)||0);const taxable=Math.max(0,subtotal-discount);const tax=Number((taxable*(Number(taxRate)||0)/100).toFixed(2));const grand=Number((taxable+tax).toFixed(2));
 function newBill(){setOpen(true);setError("");setSelectedPatient(null);setPatientQuery("");setPatients([]);setLines([]);setBillDiscount("0");setTaxRate("0");setNotes("");}
 async function createBill(e:FormEvent){e.preventDefault();if(!selectedPatient){setError("Please select a patient.");return}if(!lines.length){setError("Add at least one treatment or package.");return}setSaving(true);setError("");const form=new FormData(e.currentTarget);const appointmentId=String(form.get("appointmentId")||"");const initialPayment=Number(form.get("initialPayment")||0);const paymentMethod=String(form.get("paymentMethod")||"CASH") as Bill["payments"][number]["method"];const paymentNotes=String(form.get("paymentNotes")||"");const r=await fetch("/api/billing",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({patientId:selectedPatient.id,appointmentId,lineItems:lines,billDiscount:discount,taxRate:Number(taxRate)||0,notes,initialPayment,paymentMethod,paymentNotes})});const d=await r.json();setSaving(false);if(!r.ok){setError(d.error||"Unable to create bill.");return}setOpen(false);await load();}
 function openPayment(b:Bill){setPaymentBill(b);setPaymentAmount(b.balanceDue.toFixed(2));setPaymentMethod("CASH");setPaymentNotes("");setError("")}
 async function savePayment(e:FormEvent){e.preventDefault();if(!paymentBill)return;setSaving(true);setError("");const r=await fetch("/api/billing",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"payment",billId:paymentBill.id,amount:Number(paymentAmount),method:paymentMethod,notes:paymentNotes})});const d=await r.json();setSaving(false);if(!r.ok){setError(d.error||"Unable to record payment.");return}setPaymentBill(null);await load();}
 function printBill(b:Bill){const w=window.open("","_blank","width=800,height=900");if(!w)return;w.document.write(`<!doctype html><html><head><title>${b.billNumber}</title><style>body{font-family:Arial,sans-serif;padding:32px;color:#222}h1{margin:0 0 4px}.muted{color:#666}.right{text-align:right}table{width:100%;border-collapse:collapse;margin-top:24px}th,td{padding:8px;border-bottom:1px solid #ddd;text-align:left}th:last-child,td:last-child{text-align:right}.totals{margin-top:20px;margin-left:auto;width:320px}.row{display:flex;justify-content:space-between;padding:4px 0}.total{font-size:18px;font-weight:700;border-top:2px solid #222;margin-top:8px;padding-top:8px}@media print{body{padding:10mm}}</style></head><body><h1>Dr Dolly's Skintech Clinic</h1><div class="muted">Pratap Nagar, Nagpur, Maharashtra 440022</div><hr><div><strong>Bill No:</strong> ${b.billNumber}<br><strong>Date:</strong> ${b.billDate}<br><strong>Patient:</strong> ${b.patientNumber} · ${b.patientName}<br><strong>Mobile:</strong> ${b.mobile}</div><table><thead><tr><th>Description</th><th>Qty</th><th>Amount</th></tr></thead><tbody>${b.lineItems.map((l)=>`<tr><td>${l.name}</td><td>${l.quantity}</td><td class="right">${money(l.unitPrice*l.quantity-l.discountAmount)}</td></tr>`).join("")}</tbody></table><div class="totals"><div class="row"><span>Subtotal</span><span>${money(b.subtotal)}</span></div><div class="row"><span>Bill Discount</span><span>${money(b.billDiscount)}</span></div><div class="row"><span>Tax (${b.taxRate}%)</span><span>${money(b.taxAmount)}</span></div><div class="row total"><span>Total</span><span>${money(b.grandTotal)}</span></div><div class="row"><span>Paid</span><span>${money(b.amountPaid)}</span></div><div class="row"><span>Balance</span><span>${money(b.balanceDue)}</span></div></div><p style="margin-top:40px">Authorized Signature: ____________________</p><script>window.print();</script></body></html>`);w.document.close()}
 const filtered=bills.filter(b=>!search.trim()||b.billNumber.toLowerCase().includes(search.toLowerCase())||b.patientName.toLowerCase().includes(search.toLowerCase())||b.patientNumber.toLowerCase().includes(search.toLowerCase())||b.mobile.includes(search.trim()));
 return <><p className="eyebrow">Finance</p><div className="page-header"><div><h1>Billing & Payments</h1><p className="lead">Create bills, record payments and track outstanding balances.</p></div><button className="button" onClick={newBill}>+ New bill</button></div>
 {error&&<p className="error">{error}</p>}
 {open&&<div className="catalogue-modal-backdrop"><div className="card form-card catalogue-modal"><div className="form-header"><div><h2>New bill</h2><p className="muted">Select the patient and add treatments or packages.</p></div><button className="text-button" type="button" onClick={()=>setOpen(false)}>Close</button></div><form className="lead-form" onSubmit={createBill}>
 <label className="full">Patient{selectedPatient?<div className="card selected-patient"><strong>{selectedPatient.patientNumber} · {selectedPatient.name}</strong><span>{selectedPatient.mobile}</span><button className="text-button" type="button" onClick={()=>{setSelectedPatient(null);setPatientQuery("")}}>Change</button></div>:<><input value={patientQuery} onChange={e=>void searchPatients(e.target.value)} placeholder="Search name, mobile or Patient ID" autoComplete="off"/>{patientQuery.trim().length>=2&&<div className="card search-results">{patients.length?patients.map(p=><button className="search-result" type="button" key={p.id} onClick={()=>{setSelectedPatient(p);setPatients([])}}>{p.patientNumber} · {p.name}<small>{p.mobile}</small></button>):<span className="muted">No matching patients found.</span>}</div>}</>}</label>
 <label>Appointment ID <span className="optional">optional</span><input name="appointmentId" placeholder="Appointment ID"/></label>
 <label>Initial payment (₹)<input name="initialPayment" type="number" min="0" max={grand} step="0.01" defaultValue="0"/></label>
 <label>Payment method<select name="paymentMethod" defaultValue="CASH">{methods.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
 <div className="full"><strong>Bill items</strong><div className="card" style={{marginTop:8}}>{lines.map((l,i)=><div key={l.catalogueId+"-"+i} style={{display:"grid",gridTemplateColumns:"2fr 80px 120px 120px 100px",gap:8,alignItems:"end",marginBottom:8}}><label>Item<input readOnly value={l.name}/></label><label>Qty<input type="number" min="1" value={l.quantity} onChange={e=>updateLine(i,"quantity",e.target.value)}/></label><label>Price<input type="number" min="0" value={l.unitPrice} onChange={e=>updateLine(i,"unitPrice",e.target.value)}/></label><label>Discount<input type="number" min="0" value={l.discountAmount} onChange={e=>updateLine(i,"discountAmount",e.target.value)}/></label><button type="button" className="danger-button" onClick={()=>removeLine(i)}>Remove</button></div>)}<select defaultValue="" onChange={e=>{const id=e.target.value;if(!id)return;const item=catalogue.find(x=>x.id+"-"+x.type===id);if(item)addLine(item);e.currentTarget.value=""}}><option value="">+ Add treatment or package</option>{catalogue.map(item=><option key={item.id+"-"+item.type} value={item.id+"-"+item.type}>{item.type==="PACKAGE"?"Package: ":""}{item.name} — {money(item.price)}</option>)}</select></div></div>
 <label>Bill discount (₹)<input type="number" min="0" max={subtotal} value={billDiscount} onChange={e=>setBillDiscount(e.target.value)}/></label><label>Tax rate (%)<input type="number" min="0" max="100" step="0.01" value={taxRate} onChange={e=>setTaxRate(e.target.value)}/></label><label className="full">Notes<textarea rows={2} value={notes} onChange={e=>setNotes(e.target.value)}/></label>
 <div className="card full"><strong>Bill summary</strong><div className="row"><span>Subtotal</span><strong>{money(subtotal)}</strong></div><div className="row"><span>Discount</span><strong>{money(discount)}</strong></div><div className="row"><span>Tax</span><strong>{money(tax)}</strong></div><div className="row total"><span>Grand total</span><strong>{money(grand)}</strong></div></div>
 <div className="form-actions full"><button className="button" disabled={saving}>{saving?"Saving...":"Create bill"}</button><button type="button" className="secondary-button" onClick={()=>setOpen(false)}>Cancel</button></div></form></div></div>}
 {paymentBill&&<div className="catalogue-modal-backdrop"><div className="card form-card catalogue-modal"><div className="form-header"><div><h2>Record payment</h2><p className="muted">{paymentBill.billNumber} · Balance {money(paymentBill.balanceDue)}</p></div><button className="text-button" type="button" onClick={()=>setPaymentBill(null)}>Close</button></div><form className="lead-form" onSubmit={savePayment}><label>Amount (₹)<input required type="number" min="0.01" max={paymentBill.balanceDue} step="0.01" value={paymentAmount} onChange={e=>setPaymentAmount(e.target.value)}/></label><label>Payment method<select value={paymentMethod} onChange={e=>setPaymentMethod(e.target.value)}>{methods.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="full">Notes<textarea rows={2} value={paymentNotes} onChange={e=>setPaymentNotes(e.target.value)}/></label><div className="form-actions full"><button className="button" disabled={saving}>{saving?"Saving...":"Record payment"}</button><button type="button" className="secondary-button" onClick={()=>setPaymentBill(null)}>Cancel</button></div></form></div></div>}
 <div className="toolbar"><input className="catalogue-search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search bill, patient name, Patient ID or mobile..." /></div>
 <div className="card table-card lead-list"><div className="lead-table"><div className="lead-row catalogue-package-row lead-head"><span>Bill No.</span><span>Date</span><span>Patient</span><span>Total</span><span>Paid</span><span>Balance</span><span>Status</span><span>Actions</span></div>{filtered.map(b=><div className="lead-row catalogue-package-row" key={b.id}><strong>{b.billNumber}</strong><span>{b.billDate.split("-").reverse().join("-")}</span><span>{b.patientNumber} · {b.patientName}</span><span>{money(b.grandTotal)}</span><span>{money(b.amountPaid)}</span><span>{money(b.balanceDue)}</span><span className={b.paymentStatus==="PAID"?"status-active":"status-inactive"}>{b.paymentStatus==="PAID"?"Paid":b.paymentStatus==="PARTIALLY_PAID"?"Partially Paid":"Unpaid"}</span><span className="row-actions">{b.balanceDue>0&&<button className="text-button" onClick={()=>openPayment(b)}>Payment</button>}<button className="text-button" onClick={()=>printBill(b)}>Print</button></span></div>)}{filtered.length===0&&<div className="empty-state"><strong>No bills found</strong><span>Create a new bill to start billing.</span></div>}</div></div>
 </>;
}
