import { NextResponse } from "next/server";
import { z } from "zod";
import { requirePermission } from "@/server/auth/authorization";
import { db } from "@/server/db/prisma";

export const dynamic = "force-dynamic";
type Event={id:string;occurredAt:Date;resourceId:string|null;action:string;metadata:unknown};
const treatmentSchema=z.object({name:z.string().trim().min(2).max(160),category:z.string().trim().min(2).max(80),price:z.coerce.number().min(0).max(10000000),durationMinutes:z.coerce.number().int().min(0).max(1440),notes:z.string().trim().max(1000).optional().or(z.literal(""))});
const packageSchema=z.object({name:z.string().trim().min(2).max(160),treatmentId:z.string().uuid(),sessions:z.coerce.number().int().min(1).max(100),price:z.coerce.number().min(0).max(10000000),validityDays:z.coerce.number().int().min(1).max(3650),notes:z.string().trim().max(1000).optional().or(z.literal(""))});
const getData=(e:Event)=>(e.metadata??{}) as Record<string,unknown>;
async function events(org:string,type:string){return await db.auditEvent.findMany({where:{organizationId:org,resourceType:type},orderBy:{occurredAt:"desc"},take:5000}) as Event[];}
function current(es:Event[]){const m=new Map<string,Event>();for(const e of es){const id=e.resourceId??e.id;if(!m.has(id))m.set(id,e);}return [...m.values()].filter(e=>!e.action.endsWith("_DELETED"));}
export async function GET(){const user=await requirePermission("staff.manage");const [te,pe]=await Promise.all([events(user.organizationId,"TREATMENT"),events(user.organizationId,"TREATMENT_PACKAGE")]);const treatments=current(te).map(e=>({id:e.resourceId??e.id,...getData(e)}));const ids=new Set(treatments.map(t=>t.id));const packages=current(pe).map(e=>({id:e.resourceId??e.id,...getData(e)})).filter(p=>typeof p.treatmentId==="string"&&ids.has(p.treatmentId));return NextResponse.json({treatments,packages});}
export async function POST(req:Request){const user=await requirePermission("staff.manage");const body=await req.json();if(body.type==="treatment"){const p=treatmentSchema.safeParse(body.data);if(!p.success)return NextResponse.json({error:"Please check the treatment details."},{status:400});const es=await events(user.organizationId,"TREATMENT");if(current(es).some(e=>String(getData(e).name).toLowerCase()===p.data.name.toLowerCase()))return NextResponse.json({error:"A treatment with this name already exists."},{status:409});const id=crypto.randomUUID();await db.auditEvent.create({data:{organizationId:user.organizationId,actorUserId:user.id,resourceType:"TREATMENT",resourceId:id,action:"TREATMENT_CREATED",metadata:p.data}});return NextResponse.json({id},{status:201});}if(body.type==="package"){const p=packageSchema.safeParse(body.data);if(!p.success)return NextResponse.json({error:"Please check the package details."},{status:400});if(!current(await events(user.organizationId,"TREATMENT")).some(e=>e.resourceId===p.data.treatmentId))return NextResponse.json({error:"Selected treatment was not found."},{status:400});const id=crypto.randomUUID();await db.auditEvent.create({data:{organizationId:user.organizationId,actorUserId:user.id,resourceType:"TREATMENT_PACKAGE",resourceId:id,action:"TREATMENT_PACKAGE_CREATED",metadata:p.data}});return NextResponse.json({id},{status:201});}return NextResponse.json({error:"Invalid catalogue type."},{status:400});}
export async function PATCH(req:Request){const user=await requirePermission("staff.manage");const body=await req.json();const id=z.string().uuid().safeParse(body.id);if(!id.success)return NextResponse.json({error:"Invalid catalogue item."},{status:400});const type=body.type==="treatment"?"TREATMENT":body.type==="package"?"TREATMENT_PACKAGE":null;if(!type)return NextResponse.json({error:"Invalid catalogue type."},{status:400});const existing=current(await events(user.organizationId,type)).find(e=>e.resourceId===id.data);if(!existing)return NextResponse.json({error:"Catalogue item not found."},{status:404});const p=(type==="TREATMENT"?treatmentSchema:packageSchema).safeParse(body.data);if(!p.success)return NextResponse.json({error:"Please check the catalogue details."},{status:400});if(type==="TREATMENT"&&current(await events(user.organizationId,"TREATMENT")).some(e=>e.resourceId!==id.data&&String(getData(e).name).toLowerCase()===p.data.name.toLowerCase()))return NextResponse.json({error:"A treatment with this name already exists."},{status:409});if(type==="TREATMENT_PACKAGE"&&!current(await events(user.organizationId,"TREATMENT")).some(e=>e.resourceId===p.data.treatmentId))return NextResponse.json({error:"Selected treatment was not found."},{status:400});await db.auditEvent.create({data:{organizationId:user.organizationId,actorUserId:user.id,resourceType:type,resourceId:id.data,action:type+"_UPDATED",metadata:p.data}});return NextResponse.json({ok:true});}
export async function DELETE(req:Request){const user=await requirePermission("staff.manage");const q=new URL(req.url).searchParams;const id=z.string().uuid().safeParse(q.get("id"));const type=q.get("type");if(!id.success||!["treatment","package"].includes(type??""))return NextResponse.json({error:"Invalid catalogue item."},{status:400});const resourceType=type==="treatment"?"TREATMENT":"TREATMENT_PACKAGE";const existing=current(await events(user.organizationId,resourceType)).find(e=>e.resourceId===id.data);if(!existing)return NextResponse.json({error:"Catalogue item not found."},{status:404});await db.auditEvent.create({data:{organizationId:user.organizationId,actorUserId:user.id,resourceType,resourceId:id.data,action:resourceType+"_DELETED",metadata:getData(existing)}});return NextResponse.json({ok:true});}