import { NextResponse } from "next/server";
import { z } from "zod";
import { requirePermission } from "@/server/auth/authorization";
import { db } from "@/server/db/prisma";

export const dynamic = "force-dynamic";
type Event={id:string;occurredAt:Date;resourceId:string|null;action:string;metadata:unknown};
const treatmentSchema=z.object({name:z.string().trim().min(2).max(160),category:z.string().trim().min(2).max(80),price:z.coerce.number().min(0).max(10000000),discountPercent:z.coerce.number().min(0).max(100),discountAmount:z.coerce.number().min(0).max(10000000),durationMinutes:z.coerce.number().int().min(0).max(1440),notes:z.string().trim().max(1000).optional().or(z.literal("")),status:z.enum(["ACTIVE","INACTIVE"]).default("ACTIVE")});
const packageSchema=z.object({name:z.string().trim().min(2).max(160),treatmentId:z.string().uuid(),sessions:z.coerce.number().int().min(1).max(100),price:z.coerce.number().min(0).max(10000000),validityDays:z.coerce.number().int().min(1).max(3650),notes:z.string().trim().max(1000).optional().or(z.literal("")),status:z.enum(["ACTIVE","INACTIVE"]).default("ACTIVE")});


const standardTreatments = [
  {name:"Consultation",category:"Clinical",price:0,durationMinutes:30,notes:"Initial clinical consultation. Set clinic consultation fee if applicable."},
  {name:"Follow-up Consultation",category:"Clinical",price:0,durationMinutes:20,notes:"Follow-up clinical review."},
  {name:"Hydrafacial",category:"Facial",price:999,durationMinutes:60,notes:"Basic Hydrafacial. Current clinic offer price noted; update as required."},
  {name:"Advanced Hydrafacial",category:"Facial",price:1500,durationMinutes:60,notes:"Advanced Hydrafacial. Current clinic offer price noted; update as required."},
  {name:"Glow MediFacial",category:"Facial",price:2000,durationMinutes:60,notes:"Current clinic offer price noted; update as required."},
  {name:"MediFacial",category:"Facial",price:0,durationMinutes:60,notes:"Price to be configured."},
  {name:"Carbon Laser Facial",category:"Laser",price:0,durationMinutes:45,notes:"Price to be configured."},
  {name:"CO2 Fractional Laser",category:"Laser",price:0,durationMinutes:60,notes:"Price to be configured."},
  {name:"Q-Switched Nd:YAG Laser",category:"Laser",price:0,durationMinutes:45,notes:"Price to be configured."},
  {name:"Pico Laser",category:"Laser",price:0,durationMinutes:45,notes:"Price to be configured."},
  {name:"Laser Hair Reduction",category:"Laser Hair Reduction",price:0,durationMinutes:45,notes:"Price varies by treatment area."},
  {name:"Electrolysis",category:"Hair Removal",price:0,durationMinutes:45,notes:"For white/grey hair; price to be configured."},
  {name:"Tattoo Removal",category:"Laser",price:0,durationMinutes:45,notes:"Price varies by tattoo size and area."},
  {name:"Hair PRP",category:"Hair",price:2000,durationMinutes:60,notes:"Current single-session clinic offer price noted; update as required."},
  {name:"Hair GFC",category:"Hair",price:2800,durationMinutes:60,notes:"Current single-session clinic offer price noted; update as required."},
  {name:"Hair Patch Restoration",category:"Hair",price:0,durationMinutes:90,notes:"Non-surgical human hair patch restoration; price to be configured."},
  {name:"MNRF",category:"Skin",price:0,durationMinutes:60,notes:"Price to be configured."},
  {name:"HIFU",category:"Aesthetic",price:0,durationMinutes:60,notes:"Price varies by indication/area."},
  {name:"IV Glutathione Therapy",category:"IV Therapy",price:0,durationMinutes:60,notes:"Price to be configured according to protocol and formulation."},
  {name:"Botox",category:"Injectables",price:0,durationMinutes:45,notes:"Price depends on indication/units."},
  {name:"Dermal Fillers",category:"Injectables",price:0,durationMinutes:60,notes:"Price depends on product and quantity."},
  {name:"Thread Lift",category:"Injectables",price:0,durationMinutes:90,notes:"Price depends on area and threads used."},
  {name:"Eyebrow Microblading",category:"PMU",price:0,durationMinutes:120,notes:"Semi-permanent eyebrow procedure; price to be configured."},
  {name:"Ombre Brows",category:"PMU",price:0,durationMinutes:120,notes:"Semi-permanent eyebrow procedure; price to be configured."},
  {name:"Powder Brows",category:"PMU",price:0,durationMinutes:120,notes:"Semi-permanent eyebrow procedure; price to be configured."},
  {name:"Lip Blush",category:"PMU",price:0,durationMinutes:120,notes:"Lip pigmentation / semi-permanent makeup; price to be configured."},
  {name:"Scalp Micropigmentation",category:"PMU",price:0,durationMinutes:120,notes:"Price to be configured."},
  {name:"Earlobe Repair",category:"Minor Procedure",price:0,durationMinutes:60,notes:"Price to be configured."},
  {name:"Gunshot Ear Piercing",category:"Minor Procedure",price:0,durationMinutes:30,notes:"Price to be configured."},
  {name:"Skin Tag Removal",category:"Minor Procedure",price:0,durationMinutes:30,notes:"Price to be configured."},
  {name:"Wart Removal",category:"Minor Procedure",price:0,durationMinutes:30,notes:"Price to be configured."},
  {name:"Mole Removal",category:"Minor Procedure",price:0,durationMinutes:30,notes:"Price to be configured."},
  {name:"Chemical Peel",category:"Skin",price:0,durationMinutes:45,notes:"Price varies by peel and indication."},
  {name:"Dermaplaning",category:"Skin",price:0,durationMinutes:45,notes:"Price to be configured."},
  {name:"Microdermabrasion",category:"Skin",price:0,durationMinutes:45,notes:"Price to be configured."},
  {name:"Photofacial",category:"Skin",price:0,durationMinutes:45,notes:"Price to be configured."},
  {name:"Skin Brightening",category:"Skin",price:0,durationMinutes:45,notes:"Price to be configured."},
  {name:"BB Glow Facial",category:"Facial",price:0,durationMinutes:60,notes:"Price to be configured."},
  {name:"CC Glow Facial",category:"Facial",price:0,durationMinutes:60,notes:"Price to be configured."},
  {name:"Stretch Mark Treatment",category:"Body Aesthetics",price:0,durationMinutes:60,notes:"Price varies by area and protocol."},
  {name:"Vaginal Tightening - CO2 Laser",category:"Cosmetic Gynecology",price:0,durationMinutes:60,notes:"Price and availability to be configured."},
  {name:"Vaginal Pigmentation Treatment",category:"Cosmetic Gynecology",price:0,durationMinutes:60,notes:"Price and availability to be configured."},
  {name:"Thigh Pigmentation Treatment",category:"Body Aesthetics",price:0,durationMinutes:60,notes:"Price varies by area."},
  {name:"Vaginal Hair Laser Reduction",category:"Laser Hair Reduction",price:0,durationMinutes:45,notes:"Price to be configured."},
  {name:"Breast Tightening / Enlargement Consultation",category:"Cosmetic Gynecology",price:0,durationMinutes:45,notes:"Consultation/service details and pricing to be configured."}
];
const getData=(e:Event)=>(e.metadata??{}) as Record<string,unknown>;
async function events(org:string,type:string){return await db.auditEvent.findMany({where:{organizationId:org,resourceType:type},orderBy:{occurredAt:"desc"},take:5000}) as Event[];}
function current(es:Event[]){const m=new Map<string,Event>();for(const e of es){const id=e.resourceId??e.id;if(!m.has(id))m.set(id,e);}return [...m.values()].filter(e=>!e.action.endsWith("_DELETED"));}
export async function GET(){const user=await requirePermission("staff.manage");const [te,pe]=await Promise.all([events(user.organizationId,"TREATMENT"),events(user.organizationId,"TREATMENT_PACKAGE")]);const treatments=current(te).map(e=>{const d=getData(e);const price=Number(d.price??0);const discountPercent=Number(d.discountPercent??0);return {id:e.resourceId??e.id,status:"ACTIVE",discountPercent,discountAmount:Number(d.discountAmount??(price*discountPercent/100)),...d};});const ids=new Set(treatments.map(t=>t.id));const packages=current(pe).map(e=>({id:e.resourceId??e.id,status:"ACTIVE",...getData(e)})).filter(p=>typeof p.treatmentId==="string"&&ids.has(p.treatmentId));return NextResponse.json({treatments,packages});}
export async function POST(req:Request){const user=await requirePermission("staff.manage");const body=await req.json();if(body.action==="seed-standard"){const existing=current(await events(user.organizationId,"TREATMENT"));const existingNames=new Set(existing.map(e=>String(getData(e).name).toLowerCase()));let created=0;const idsByName=new Map<string,string>();for(const e of existing)idsByName.set(String(getData(e).name).toLowerCase(),e.resourceId??e.id);for(const treatment of standardTreatments){if(existingNames.has(treatment.name.toLowerCase()))continue;const id=crypto.randomUUID();await db.auditEvent.create({data:{organizationId:user.organizationId,actorUserId:user.id,resourceType:"TREATMENT",resourceId:id,action:"TREATMENT_CREATED",metadata:treatment}});idsByName.set(treatment.name.toLowerCase(),id);created++;}const prpId=idsByName.get("hair prp");if(prpId){const packages=current(await events(user.organizationId,"TREATMENT_PACKAGE"));if(!packages.some(e=>String(getData(e).name).toLowerCase()==="hair prp - 6 sessions"))await db.auditEvent.create({data:{organizationId:user.organizationId,actorUserId:user.id,resourceType:"TREATMENT_PACKAGE",resourceId:crypto.randomUUID(),action:"TREATMENT_PACKAGE_CREATED",metadata:{name:"Hair PRP - 6 Sessions",treatmentId:prpId,sessions:6,price:10000,validityDays:180,notes:"Current clinic package offer."}}});}return NextResponse.json({created,message:created?"Standard treatment catalogue added.":"Standard treatment catalogue was already present."});}if(body.type==="treatment"){const p=treatmentSchema.safeParse(body.data);if(!p.success)return NextResponse.json({error:"Please check the treatment details."},{status:400});const es=await events(user.organizationId,"TREATMENT");if(current(es).some(e=>String(getData(e).name).toLowerCase()===p.data.name.toLowerCase()))return NextResponse.json({error:"A treatment with this name already exists."},{status:409});const id=crypto.randomUUID();await db.auditEvent.create({data:{organizationId:user.organizationId,actorUserId:user.id,resourceType:"TREATMENT",resourceId:id,action:"TREATMENT_CREATED",metadata:p.data}});return NextResponse.json({id},{status:201});}if(body.type==="package"){const p=packageSchema.safeParse(body.data);if(!p.success)return NextResponse.json({error:"Please check the package details."},{status:400});if(!current(await events(user.organizationId,"TREATMENT")).some(e=>e.resourceId===p.data.treatmentId))return NextResponse.json({error:"Selected treatment was not found."},{status:400});const id=crypto.randomUUID();await db.auditEvent.create({data:{organizationId:user.organizationId,actorUserId:user.id,resourceType:"TREATMENT_PACKAGE",resourceId:id,action:"TREATMENT_PACKAGE_CREATED",metadata:p.data}});return NextResponse.json({id},{status:201});}return NextResponse.json({error:"Invalid catalogue type."},{status:400});}
export async function PATCH(req:Request){const user=await requirePermission("staff.manage");const body=await req.json();const id=z.string().uuid().safeParse(body.id);if(!id.success)return NextResponse.json({error:"Invalid catalogue item."},{status:400});const type=body.type==="treatment"?"TREATMENT":body.type==="package"?"TREATMENT_PACKAGE":null;if(!type)return NextResponse.json({error:"Invalid catalogue type."},{status:400});const existing=current(await events(user.organizationId,type)).find(e=>e.resourceId===id.data);if(!existing)return NextResponse.json({error:"Catalogue item not found."},{status:404});const p=(type==="TREATMENT"?treatmentSchema:packageSchema).safeParse(body.data);if(!p.success)return NextResponse.json({error:"Please check the catalogue details."},{status:400});if(type==="TREATMENT"&&current(await events(user.organizationId,"TREATMENT")).some(e=>e.resourceId!==id.data&&String(getData(e).name).toLowerCase()===p.data.name.toLowerCase()))return NextResponse.json({error:"A treatment with this name already exists."},{status:409});if(type==="TREATMENT_PACKAGE"&&!current(await events(user.organizationId,"TREATMENT")).some(e=>e.resourceId===p.data.treatmentId))return NextResponse.json({error:"Selected treatment was not found."},{status:400});await db.auditEvent.create({data:{organizationId:user.organizationId,actorUserId:user.id,resourceType:type,resourceId:id.data,action:type+"_UPDATED",metadata:p.data}});return NextResponse.json({ok:true});}
export async function DELETE(req:Request){const user=await requirePermission("staff.manage");const q=new URL(req.url).searchParams;const id=z.string().uuid().safeParse(q.get("id"));const type=q.get("type");if(!id.success||!["treatment","package"].includes(type??""))return NextResponse.json({error:"Invalid catalogue item."},{status:400});const resourceType=type==="treatment"?"TREATMENT":"TREATMENT_PACKAGE";const existing=current(await events(user.organizationId,resourceType)).find(e=>e.resourceId===id.data);if(!existing)return NextResponse.json({error:"Catalogue item not found."},{status:404});await db.auditEvent.create({data:{organizationId:user.organizationId,actorUserId:user.id,resourceType,resourceId:id.data,action:resourceType+"_DELETED",metadata:getData(existing)}});return NextResponse.json({ok:true});}